const s = {
  topRow:        { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' },
  contador:      { fontSize: '14px', color: '#888' },
  filtrosBox:    { display: 'flex', flexWrap: 'wrap', gap: '8px', alignItems: 'center', background: 'white', borderRadius: '10px', padding: '14px 16px', marginBottom: '10px', boxShadow: '0 1px 4px rgba(0,0,0,0.07)' },
  ordenBox:      { display: 'flex', gap: '8px', alignItems: 'center', background: 'white', borderRadius: '10px', padding: '10px 16px', marginBottom: '20px', boxShadow: '0 1px 4px rgba(0,0,0,0.07)' },
  filtrosLabel:  { fontSize: '13px', fontWeight: '600', color: '#555', marginRight: '4px' },
  filtroInput:   { padding: '7px 12px', borderRadius: '7px', border: '1px solid #ddd', fontSize: '13px', outline: 'none', width: '130px' },
  select:        { padding: '7px 10px', borderRadius: '7px', border: '1px solid #ddd', fontSize: '13px', background: 'white' },
  propGrid:      { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '16px', marginBottom: '28px' },
  propCard:      { background: 'white', borderRadius: '12px', padding: '18px', boxShadow: '0 2px 8px rgba(0,0,0,0.08)', cursor: 'pointer', transition: 'box-shadow 0.2s' },
  propCardTop:   { display: 'flex', alignItems: 'center', marginBottom: '10px', gap: '8px' },
  propIcono:     { fontSize: '28px' },
  propIdTag:     { fontSize: '11px', color: '#888', background: '#f0f0f0', borderRadius: '999px', padding: '2px 8px', flex: 1 },
  propAcciones:  { display: 'flex', gap: '4px' },
  btnIcono:      { background: 'none', border: 'none', cursor: 'pointer', fontSize: '16px', padding: '2px 4px', borderRadius: '4px' },
  propNombre:    { fontWeight: '700', fontSize: '16px', color: '#1a1a2e', margin: '0 0 4px' },
  propDir:       { fontSize: '13px', color: '#888', margin: '0 0 2px' },
  propFecha:     { fontSize: '11px', color: '#bbb', margin: '6px 0 0' },
  deptoGrid:     { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(190px, 1fr))', gap: '12px' },
  deptoCard:     { background: '#f7f9fc', borderRadius: '10px', padding: '14px', display: 'flex', flexDirection: 'column', gap: '10px' },
  deptoHeader2:  { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  deptoNum:      { fontSize: '15px', fontWeight: '700', color: '#1a1a2e' },
  badge:         { fontSize: '11px', fontWeight: '600', padding: '3px 10px', borderRadius: '999px' },
  deptoInfo:     { display: 'flex', gap: '16px', paddingTop: '8px', borderTop: '1px solid #e8e8e8' },
  infoItem:      { display: 'flex', flexDirection: 'column', gap: '2px' },
  infoLabel:     { fontSize: '11px', color: '#aaa', textTransform: 'uppercase', letterSpacing: '0.05em' },
  infoVal:       { fontSize: '14px', fontWeight: '600', color: '#333' },
  seccion:       { marginBottom: '20px', paddingBottom: '16px', borderBottom: '1px solid #f0f0f0' },
  seccionTitulo: { fontSize: '13px', fontWeight: '700', color: '#0f3460', textTransform: 'uppercase', letterSpacing: '0.05em', margin: '0 0 10px' },
  datosGrid:     { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))', gap: '12px' },
  overlay:       { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 },
  modal:         { background: 'white', borderRadius: '14px', padding: '28px', width: '100%', maxHeight: '85vh', overflowY: 'auto', boxShadow: '0 20px 60px rgba(0,0,0,0.3)' },
  modalHeader:   { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' },
  modalTitulo:   { margin: 0, fontSize: '18px', fontWeight: '700', color: '#1a1a2e' },
  btnCerrar:     { background: 'none', border: 'none', fontSize: '18px', cursor: 'pointer', color: '#888' },
  modalBtns:     { display: 'flex', justifyContent: 'flex-end', gap: '10px', marginTop: '16px' },
  label:         { display: 'block', fontSize: '13px', fontWeight: '600', color: '#333', marginBottom: '4px' },
  input:         { width: '100%', padding: '9px 12px', borderRadius: '7px', border: '1px solid #ddd', fontSize: '14px', boxSizing: 'border-box', outline: 'none' },
  btnPrimario:   { padding: '9px 18px', borderRadius: '7px', border: 'none', background: '#0f3460', color: 'white', fontSize: '14px', fontWeight: '600', cursor: 'pointer' },
  btnSecundario: { padding: '9px 18px', borderRadius: '7px', border: '1px solid #ddd', background: 'white', color: '#333', fontSize: '14px', cursor: 'pointer' },
  error:         { color: '#c0392b', fontSize: '13px', margin: '8px 0 0' },
}

export default s
